[package]
name = "csv_to_snowflake"
version = "0.1.0"
edition = "2024"

[dependencies]
snowflake-api = "0.12.0"
anyhow = "1.0.98"
tokio = { version = "1.45.0", features = ["full"]}
csv = "1.2"
serde = { version = "1.0", features = ["derive"] }
