// Automatically generated by Interoptopus.

#pragma warning disable 0105
using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using Interop;
#pragma warning restore 0105

namespace Interop
{
    public static partial class InteropClass
    {
        public const string NativeLib = "bkash_api";

        static InteropClass()
        {
        }


        /// Function using the type.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "my_function")]
        public static extern uint MyFunction(Rectangle rect);

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "print_string")]
        public static extern void PrintString([MarshalAs(UnmanagedType.LPUTF8Str)] string utf8Text);

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "get_text")]
        private static extern System.IntPtr GetText();

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "free_text")]
        private static extern void FreeText(System.IntPtr s);

        public static string GetTextData()
        {
            System.IntPtr tempPointer = GetText();
            string tempString = Marshal.PtrToStringAnsi(tempPointer);

            string ver = (string)tempString.Clone();

            FreeText(tempPointer);

            return ver;
        }

    }

    /// A simple type in our FFI layer.
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct Rectangle
    {
        public uint width;
        public uint height;
    }



    public class InteropException<T> : Exception
    {
        public T Error { get; private set; }

        public InteropException(T error) : base($"Something went wrong: {error}")
        {
            Error = error;
        }
    }

}
