// Automatically generated by Interoptopus.

#pragma warning disable 0105
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.InteropServices;
using Interop;
#pragma warning restore 0105

namespace Interop
{
    public static partial class InteropClass
    {
        public const string NativeLib = "bkash_api";

        static InteropClass()
        {
        }

        /// Function using the type.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "my_function")]
        public static extern uint MyFunction(Rectangle rect);

        /// Function using the type.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "get_length")]
        public static extern uint GetLength([MarshalAs(UnmanagedType.LPUTF8Str)] string text);

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "get_text")]
        private static extern System.IntPtr GetText();

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "free_text")]
        private static extern void FreeText(System.IntPtr s);

        public static string GetTextData()
        {
            var tempPointer = GetText();
            var tempString = Marshal.PtrToStringAnsi(tempPointer);

            var textData = (string)tempString.Clone();

            FreeText(tempPointer);

            return textData;
        }
    }

    /// A simple type in our FFI layer.
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct Rectangle
    {
        public uint width;
        public uint height;

        public Rectangle(uint width, uint height)
        {
            this.width  = width;
            this.height = height;
        }
    }



    public class InteropException<T> : Exception
    {
        public T Error { get; private set; }

        public InteropException(T error): base($"Something went wrong: {error}")
        {
            Error = error;
        }
    }

}