[package]
name = "tesseract_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3"
leptess = "0.14"
image = "0.24"
opencv = { version = "0.86", features = ["clang-runtime"] }
base64 = "0.21"
serde = { version = "1.0", features = ["derive"] }
