[package]
name = "dist_sys"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40", features = ["full"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.128"
anyhow = "1.0"
