[package]
name = "chatterbox"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = [
    "io-util",
    "io-std",
    "net",
    "macros",
    "rt-multi-thread",
] }
clap = { version = "4.5", features = ["derive"] }
